name: Analyze
permissions:
  contents: read

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-8.2-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            dependencies-php-8.2-composer-
            dependencies-php-

      - name: Install Composer dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: composer analyze
